# Generated by Django 5.1.1 on 2025-04-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyance_app', '0006_alter_conveyancemodel_end_journey_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveyancemodel',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conveyancemodel',
            name='time_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
