# Generated by Django 5.1.1 on 2025-04-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyance_app', '0007_update_conveyance_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaMovementInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('da_code', models.CharField(max_length=50)),
                ('mv_date', models.DateField()),
                ('time_duration', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
