# Generated by Django 5.1.1 on 2025-04-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conveyance_app', '0008_add_da_movement_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damovementinfo',
            options={'verbose_name': 'DaMovementInfo', 'verbose_name_plural': 'DaMovementInfo'},
        ),
        migrations.AlterModelTable(
            name='damovementinfo',
            table='rdl_da_movement_info',
        ),
    ]
