# Generated by Django 5.1.1 on 2025-08-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conveyance_app", "0009_update_da_movement_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conveyancemodel",
            name="distance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="conveyancemodel",
            name="time_duration",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
