# Generated by Django 5.1.1 on 2025-08-03 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_app", "0001_initial"),
        ("user_app", "0008_alter_userslist_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancemodel",
            name="sap_id",
            field=models.ForeignKey(
                db_column="sap_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="user_app.userslist",
            ),
        ),
    ]
