# Generated by Django 5.1.1 on 2024-11-07 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnlistsapmodel',
            name='sales_quantity',
        ),
        migrations.AddField(
            model_name='returnsapmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 12, 13, 30, 34, 525694)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnsapmodel',
            name='da_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnsapmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
