# Generated by Django 5.1.1 on 2024-11-07 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_app', '0002_remove_returnlistsapmodel_sales_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnlistsapmodel',
            old_name='return_no',
            new_name='return_id',
        ),
        migrations.AddField(
            model_name='returnlistsapmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 12, 13, 30, 34, 525694)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlistsapmodel',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlistsapmodel',
            name='sales_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlistsapmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
