# Generated by Django 5.1.1 on 2024-11-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_app', '0003_rename_return_no_returnlistsapmodel_return_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnsapmodel',
            name='return_product_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnsapmodel',
            name='sales_product_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
