# Generated by Django 5.1.1 on 2024-11-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_app', '0004_returnsapmodel_return_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnsapmodel',
            name='return_reason',
            field=models.IntegerField(choices=[(901, 'Wrong Order'), (902, 'Pharmacy Closed'), (903, 'Customer Denied to Accept'), (904, 'No Order'), (905, 'Cash Short'), (906, 'Delayed Delivery'), (907, 'Damaged Goods'), (908, 'Price Difference'), (909, 'Quantity Discrepancy'), (910, 'Discount Discrepancy'), (911, 'Order Mistakenly Created'), (912, 'Out of Schedule'), (913, 'Route Cancelled'), (914, 'Natural Disaster'), (915, 'Short Dated Material'), (916, 'Rate Increase'), (917, 'Patient No More Alive'), (918, 'Mistakenly Created By Depot'), (919, 'PQC')]),
        ),
        migrations.AlterField(
            model_name='returnsapmodel',
            name='return_type',
            field=models.CharField(choices=[('p', 'p'), ('f', 'f')], max_length=1),
        ),
    ]
