# Generated by Django 5.1.1 on 2024-11-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('build_number', models.CharField(max_length=20)),
                ('force_to_update', models.BooleanField(default=True)),
                ('remove_cache_on_update', models.BooleanField(default=False)),
                ('remove_data_on_update', models.BooleanField(default=False)),
                ('remove_cache_and_data_on_update', models.BooleanField(default=False)),
                ('main_file', models.FileField(upload_to='apks/')),
                ('x86_64_file', models.FileField(blank=True, null=True, upload_to='apks/')),
                ('armeabi_v7a_file', models.FileField(blank=True, null=True, upload_to='apks/')),
                ('arm64_v8a_file', models.FileField(blank=True, null=True, upload_to='apks/')),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ODMS Mobile App',
                'verbose_name_plural': 'ODMS Mobile App',
                'db_table': 'rdl_odms_mobile_app',
            },
        ),
    ]
