# Generated by Django 5.1.1 on 2024-12-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_userlist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersList',
            fields=[
                ('sap_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('Delivery Assistant', 'Delivery Assistant'), ('Driver', 'Driver')], max_length=20, null=True)),
                ('user_designation', models.CharField(blank=True, max_length=55, null=True)),
                ('user_depot', models.CharField(blank=True, max_length=155, null=True)),
                ('user_job_location', models.CharField(blank=True, max_length=155, null=True)),
                ('password', models.CharField(max_length=55)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'RDL Users List',
                'verbose_name_plural': 'RDL Users List',
                'db_table': 'rdl_users_list',
            },
        ),
    ]
