# Generated by Django 5.1.1 on 2025-01-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_userslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslist',
            name='depot_code',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
