# Generated by Django 5.1.1 on 2025-08-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0007_userslist_depot_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userslist",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Distribution Assistant", "Distribution Assistant"),
                    ("Driver", "Driver"),
                ],
                max_length=55,
                null=True,
            ),
        ),
    ]
